# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newwind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QFileDialog
from PIL import ImageGrab

output_location = r'.\Resourses\images\image.png'

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("color: ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.download_btn = QtWidgets.QPushButton(self.centralwidget)
        self.download_btn.setGeometry(QtCore.QRect(125, 20, 250, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        self.download_btn.setFont(font)
        self.download_btn.setStyleSheet("background-color: #4b4bd6;\n"
"color: white;\n"
"")
        self.download_btn.setObjectName("download_btn")
        self.paste_btn = QtWidgets.QPushButton(self.centralwidget)
        self.paste_btn.setGeometry(QtCore.QRect(125, 160, 250, 70))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.paste_btn.setFont(font)
        self.paste_btn.setStyleSheet("background-color: #4b4bd6;\n"
"color: white;\n"
"")
        self.paste_btn.setObjectName("paste_btn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(75, 380, 350, 180))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.getText_btn = QtWidgets.QPushButton(self.frame)
        self.getText_btn.setGeometry(QtCore.QRect(0, 0, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(12)
        self.getText_btn.setFont(font)
        self.getText_btn.setStyleSheet("background-color: #4b4bd6;\n"
"color: white")
        self.getText_btn.setObjectName("getText_btn")
        self.textArea = QtWidgets.QTextEdit(self.frame)
        self.textArea.setGeometry(QtCore.QRect(0, 30, 350, 150))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(10)
        self.textArea.setFont(font)
        self.textArea.setStyleSheet("color: white;")
        self.textArea.setObjectName("textArea")
        self.or_text = QtWidgets.QLabel(self.centralwidget)
        self.or_text.setGeometry(QtCore.QRect(210, 95, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.or_text.setFont(font)
        self.or_text.setStyleSheet("color: #4b4bd6;")
        self.or_text.setObjectName("or_text")
        self.status_btn = QtWidgets.QLabel(self.centralwidget)
        self.status_btn.setGeometry(QtCore.QRect(100, 325, 300, 40))
        self.status_btn.setAlignment(Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        self.status_btn.setFont(font)
        self.status_btn.setStyleSheet("color: #4b4bd6;")
        self.status_btn.setText("")
        self.status_btn.setObjectName("status_btn")
        self.lang_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.lang_combobox.setGeometry(QtCore.QRect(100, 280, 300, 35))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(10)
        self.lang_combobox.setFont(font)
        self.lang_combobox.setStyleSheet("color: white;")
        self.lang_combobox.setObjectName("lang_combobox")
        self.lang_combobox.addItem("")
        self.lang_combobox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(212, 240, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #4b4bd6;")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.download_btn.setText(_translate("MainWindow", "Загрузить картинку"))
        self.paste_btn.setText(_translate("MainWindow", "Вставить картинку"))
        self.getText_btn.setText(_translate("MainWindow", "Получить текст"))
        self.or_text.setText(_translate("MainWindow", "или"))
        self.lang_combobox.setItemText(0, _translate("MainWindow", "Русский"))
        self.lang_combobox.setItemText(1, _translate("MainWindow", "Английский"))
        self.label.setText(_translate("MainWindow", "Язык"))

    def add_functions(self):
        self.download_btn.clicked.connect(self.download_img)
        self.paste_btn.clicked.connect(self.paste_img)

    def download_img(self):
        file = QFileDialog.getOpenFileName(None, 'Open File', './', "Image (*.png *.jpg *jpeg)")
        self.status_btn.setText("Картинка загружена")
        return file

    def paste_img(self):
        try:
            image = ImageGrab.grabclipboard()
            self.status_btn.setText("Картинка загружена")
            image.save(output_location, 'PNG')
            return '.\Resourses\images\image.png'
        except:
            self.status_btn.setText("Файл не картнинка!")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
